# Generated by Django 5.2.4 on 2025-08-05 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('mod_id', models.CharField(help_text='Insira o ID do mod.', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('workshop_id', models.CharField(help_text='Insira o ID do workshop do mod.', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('name', models.CharField(help_text='Insira o nome do mod.', max_length=100)),
                ('mod_link', models.URLField(blank=True, help_text='Insira o link do mod.')),
                ('suggested_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora em que o mod foi sugerido.')),
                ('suggested_by', models.ForeignKey(blank=True, help_text='Insira o nome do usuário que sugeriu o mod.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mod',
                'verbose_name_plural': 'Mods',
                'ordering': ['-suggested_at'],
            },
        ),
    ]
