# Generated by Django 5.2.4 on 2025-08-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='status',
            field=models.CharField(choices=[('enabled', 'Habilitado'), ('disabled', 'Desabilitado')], default='disabled', max_length=10),
        ),
    ]
