#!/bin/bash
cd $HOME

# Install java / dependencies
apt update && sudo apt full-upgrade -y
apt install -y git build-essential cmake gcc-arm-linux-gnueabihf openjdk-21-jdk unzip

# Enable ARM hard float architecture / install dependencies
dpkg --add-architecture armhf && sudo apt update
apt install -y libc6:armhf libncurses6:armhf libstdc++6:armhf

# FEX-Emu Setup (Emulador ultra-preciso para substituir o Box64)
sudo add-apt-repository ppa:fex-emu/fex -y
sudo apt update
sudo apt install -y fex-emu-arm64

# Faz o download do sistema de arquivos x86_64 para o FEX
FEXRootFSFetcher -y


# DepotDownloader setup (Substituto nativo e mais rapido para o SteamCMD no ARM)
mkdir -p depotdownloader && cd depotdownloader
curl -sqL -o depotdownloader.zip "https://github.com/SteamRE/DepotDownloader/releases/latest/download/DepotDownloader-linux-arm64.zip"
unzip -q -o depotdownloader.zip
chmod +x DepotDownloader


############################################################################################
#################### download and install zomboid server version ####################
############################################################################################
mkdir -p /opt/zomboid-server

# Let the user define which zomboid version to install
read -p "do you want to run a beta branch? (y/n) otherwise, current release will be used: " use_beta
if [[ "$use_beta" =~ ^[Yy]$ ]]; then
    read -p 'Please specify the version (i.e. 42.13.3), otherwise "unstable" will be used: ' beta_version
    beta_version=${beta_version:-unstable}
    echo "installing beta $beta_version"
    ./DepotDownloader -app 380870 -os linux -beta "$beta_version" -dir /opt/zomboid-server/
else
    echo "installing current release"
    ./DepotDownloader -app 380870 -os linux -dir /opt/zomboid-server/
fi
############################################################################################
############################################################################################

# Prompt user for manual config
read -p "Please, without interrupting this script, start the server manually in another terminal and set the password. Press Enter when that's done..."

# Fix up some dependencies and paths for server files
ln -sf /opt/zomboid-server/linux64/steamclient.so /opt/zomboid-server/linux64/libsteam.so
ln -s /root/Zomboid/* /opt/zomboid-server/ # Had to keep this, because -cache-dir flag gives issues

# Set up zomboid as a systemd service
tee /etc/systemd/system/zomboid-server.service > /dev/null <<EOL
[Unit]
Description=Project Zomboid Server
After=network.target

[Service]
User=$(whoami)
WorkingDirectory=/opt/zomboid-server/

# IMPORTANT: force data directory + prevent LD_PRELOAD issues
ExecStart=/usr/bin/FEXBash -c '/opt/zomboid-server/start-server.sh'

Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOL

systemctl daemon-reload
source /usr/share/bash-completion/completions/systemctl
systemctl enable zomboid-server && sudo systemctl start zomboid-server
